Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu-14.04-amd64'
  config.vm.box_url = 'https://oss-binaries.phusionpassenger.com/vagrant/boxes/latest/ubuntu-14.04-amd64-vbox.box'
  config.vm.synced_folder '../../', '/src', nfs: true
  config.ssh.forward_agent = true
  config.vm.provision 'ansible' do |ansible|
    ansible.playbook = 'src.yml'
  end
end
